
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysmxjpedzosqaijvzhfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzbXhqcGVkem9zcWFpanZ6aGZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNTAwNDcsImV4cCI6MjA2MzYyNjA0N30.1Uq5j_RskpDmXJl2GAuGcUp5m_xDE0JRDnbRGE2yAjc";

// Configure Supabase client with proper auth settings
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
